name: Lint with flake8
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-html
          pip install -r requirements.txt

      - name: Generate flake8 HTML report (non-fatal) and run strict check
        run: |
          rm -rf flake8_report
          mkdir -p flake8_report
          
          flake8 . --max-line-length=119 --format=html --htmldir=flake8_report || true
          flake8 . --max-line-length=119

      - name: Upload flake8 report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flake8_report
          path: flake8_report/**

      - name: Commit updated HTML report to repo
        if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add flake8_report
          git commit -m "CI: update flake8 HTML report [skip ci]" || echo "No changes to commit"
          git push
